# Generated by Django 5.1.3 on 2024-11-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_image'),
    ]

    operations = [
    ]
