# Generated by Django 5.1.3 on 2024-11-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20241130_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bahan',
            field=models.CharField(default='Tidak Diketahui', max_length=50),
        ),
    ]
