# Generated by Django 5.1.3 on 2024-11-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_bahan'),
    ]

    operations = [
    ]
